In [4]:
import pandas as pd
import seaborn  as sns
import matplotlib.pyplot as plt
# Load dataset

# Load dataset
def load_repositary1(file_path):
  return pd.read_csv(file_path)


df = load_repositary1("./Health_heart_experimental.csv")
df.head(5)

,Unnamed: 0,age,sex,SysBP,DiaBP,HR,weightKg,heightCm,BMI,indication
0,0,64,1,141,96,128,69,147,32.0,1
1,1,21,1,109,100,106,48,150,21.0,0
2,2,30,0,112,73,126,69,183,21.0,0
3,3,35,1,106,90,130,45,149,20.0,0
4,4,39,0,140,90,112,92,166,33.0,1